name: Run Telegram Bot

on:
  workflow_dispatch:  # Запуск вручную из вкладки Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Клонируем код
      uses: actions/checkout@v3

    - name: 🐍 Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📥 Устанавливаем зависимости
      run: |
        pip install -r requirements.txt

    - name: 🚀 Запускаем бота
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        python3 main.py
